### Site settings
title: João Paulo D. Lima
description: PhD Candidate in Development Economics

baseurl: ""
url: "https://limajoaopaulo.github.io"
email: joaop.dlima@gmail.com

# Pagination (disabled — no blog)
# paginate: 4
# permalink: /blog/:year/:title/
# paginate_path: /blog/page:num/

# Social media links in footer
linkedin: "joão-paulo-duarte-lima-991510a1"
github: "limajoaopaulo"
researchgate: "Joao-Paulo-Lima-8"
orcid: ""

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

# collections (none currently)

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-target-blank
